
SELECT TOP 100 ASCEDING.RNK, I1.I_PRODUCT_NAME BEST_PERFORMING, I2.I_PRODUCT_NAME WORST_PERFORMING
FROM(SELECT *
     FROM (SELECT ITEM_SK,RANK() OVER (ORDER BY RANK_COL ASC) RNK
           FROM (SELECT SS_ITEM_SK ITEM_SK,AVG(SS_NET_PROFIT) RANK_COL
                 FROM STORE_SALES SS1
                 WHERE SS_STORE_SK = 10
                 GROUP BY SS_ITEM_SK
                 HAVING AVG(SS_NET_PROFIT) > 0.9*(SELECT AVG(SS_NET_PROFIT) RANK_COL
                                                  FROM STORE_SALES
                                                  WHERE SS_STORE_SK = 10
                                                    AND SS_CUSTOMER_SK IS NULL AND SS_CDEMO_SK IS NULL AND SS_HDEMO_SK IS NULL AND SS_ADDR_SK IS NULL AND SS_PROMO_SK IS NULL
                                                  GROUP BY SS_STORE_SK))V1)V11
     WHERE RNK  < 11) ASCEDING,
    (SELECT *
     FROM (SELECT ITEM_SK,RANK() OVER (ORDER BY RANK_COL DESC) RNK
           FROM (SELECT SS_ITEM_SK ITEM_SK,AVG(SS_NET_PROFIT) RANK_COL
                 FROM STORE_SALES SS1
                 WHERE SS_STORE_SK = 10
                 GROUP BY SS_ITEM_SK
                 HAVING AVG(SS_NET_PROFIT) > 0.9*(SELECT AVG(SS_NET_PROFIT) RANK_COL
                                                  FROM STORE_SALES
                                                  WHERE SS_STORE_SK = 10
                                                    AND SS_CUSTOMER_SK IS NULL AND SS_CDEMO_SK IS NULL AND SS_HDEMO_SK IS NULL AND SS_ADDR_SK IS NULL AND SS_PROMO_SK IS NULL
                                                  GROUP BY SS_STORE_SK))V2)V21
     WHERE RNK  < 11) DESCENDING,
    ITEM I1,
    ITEM I2
WHERE ASCEDING.RNK = DESCENDING.RNK
  AND I1.I_ITEM_SK=ASCEDING.ITEM_SK
  AND I2.I_ITEM_SK=DESCENDING.ITEM_SK
ORDER BY ASCEDING.RNK