SELECT ID, GROUPBY, SEARCH, ORDERBY
FROM (
         SELECT ID, GROUPBY, SEARCH, ORDERBY,
                DENSE_RANK() OVER (PARTITION BY GROUPBY ORDER BY ID) RD1,
                DENSE_RANK() OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID) RD2,
                DENSE_RANK() OVER (PARTITION BY GROUPBY ORDER BY ID) RD3
         FROM A
         WHERE GROUPBY IS NULL OR GROUPBY > 90 AND ID IS NOT NULL
     ) T1
    CROSS JOIN  (
        SELECT RANK() OVER (PARTITION BY GROUPBY ORDER BY ID) RD4
        FROM A
        WHERE GROUPBY IS NULL OR GROUPBY > 90 AND ID IS NOT NULL
    ) T2
WHERE (RD1 = 1 OR RD2 = 5 OR RD3 < 3) AND RD4 < 2
ORDER BY ID, GROUPBY