SELECT ID, GROUPBY
FROM (
         SELECT ID, GROUPBY,
                RANK() OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID) RD1
         FROM A
         WHERE GROUPBY IS NULL OR GROUPBY > 90 AND ID IS NOT NULL
     ) T1
WHERE RD1 < 30
UNION ALL
SELECT ID, GROUPBY
FROM (
    SELECT ID, GROUPBY,
           DENSE_RANK() OVER (PARTITION BY GROUPBY ORDER BY ID) RD2
    FROM A
    WHERE GROUPBY IS NULL OR GROUPBY > 90 AND ID IS NOT NULL
) T2
WHERE RD2 = 1
ORDER BY ID, GROUPBY