SELECT ID, GROUPBY
FROM (
         SELECT ID, GROUPBY,
                RANK() OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID) RD1,
                ROW_NUMBER() OVER (ORDER BY ID) RD2
         FROM A
         WHERE GROUPBY IS NULL OR GROUPBY > 90 AND ID IS NOT NULL
     ) T1
CROSS JOIN  (
    SELECT RANK() OVER (PARTITION BY GROUPBY ORDER BY ID) RD3
    FROM A
    WHERE GROUPBY IS NULL OR GROUPBY > 90 AND ID IS NOT NULL
) T2
WHERE RD1 < 30 AND RD2 < 100 AND RD3 = 1
ORDER BY ID, GROUPBY