SELECT ID, GROUPBY
FROM (
         SELECT ID, GROUPBY,
                RANK() OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID) RD
         FROM A
         WHERE GROUPBY IS NULL OR GROUPBY > 90
     ) T1
WHERE RD < 3
ORDER BY GROUPBY, ID