SELECT *
FROM (
         SELECT ID, GROUPBY, ORDERBY,  SEARCH, FKB,
                LAG(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID) LAG_FKB1,
                LEAD(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID) LEAD_FKB1,
                LAG(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID) LAG_FKB2,
                LEAD(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID) LEAD_FKB2,
                LAG(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY DESC, SEARCH DESC, ID) LAG_FKB3,
                LEAD(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY DESC, SEARCH DESC, ID) LEAD_FKB3
         FROM A
     ) T1
JOIN (
        SELECT ID T2_ID,
            LAG(FKB) OVER (ORDER BY ORDERBY DESC, SEARCH DESC, ID) LAG_FKB4,
                LEAD(FKB) OVER (ORDER BY ORDERBY DESC, SEARCH DESC, ID) LEAD_FKB4
        FROM A
        WHERE GROUPBY > 90
    ) T2 ON T1.ID = T2.T2_ID
WHERE ID > 90900
ORDER BY GROUPBY, ORDERBY, ID