SELECT *
FROM (
         SELECT ID, GROUPBY, ORDERBY,  SEARCH, FKB,
                MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID ROWS 1 PRECEDING) MIN_FKB0,
                MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING) MIN_FKB1,
                MAX(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID DESC ROWS BETWEEN 4 PRECEDING AND 1 PRECEDING) MAX_FKB1,
                MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH, ID DESC ROWS BETWEEN 4 PRECEDING AND CURRENT ROW ) MIN_FKB2,
                MAX(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN 4 PRECEDING AND CURRENT ROW ) MAX_FKB2,
             -- MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN 4 PRECEDING AND 1 FOLLOWING) MIN_FKB3,
             -- MAX(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN 4 PRECEDING AND 1 FOLLOWING) MAX_FKB3,
                MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING ) MIN_FKB4,
                MAX(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN CURRENT ROW AND 5 FOLLOWING ) MAX_FKB4,
             MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING ) MIN_FKB5,
                 MAX(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY, SEARCH DESC, ID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING ) MAX_FKB5,
                MIN(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY DESC, SEARCH, ID ROWS BETWEEN 2 FOLLOWING AND UNBOUNDED FOLLOWING ) MIN_FKB6,
                MAX(FKB) OVER (PARTITION BY GROUPBY ORDER BY ORDERBY DESC, SEARCH, ID ROWS BETWEEN 2 FOLLOWING AND UNBOUNDED FOLLOWING ) MAX_FKB6
         FROM A
     ) T1
JOIN (
        SELECT ID T2_ID,
               -- AVG(FKB) OVER (ORDER BY ORDERBY, ID ROWS BETWEEN 2 PRECEDING AND 10 FOLLOWING ) AVG_FKB1,
               AVG(FKB) OVER (ORDER BY ORDERBY, ID ROWS 5 PRECEDING) AVG_FKB2
        FROM A
        WHERE GROUPBY > 95
    ) T2 ON T1.ID = T2.T2_ID
WHERE ID > 90900
ORDER BY GROUPBY, ORDERBY, ID